[global]

[hasura]
version = 'v2.25.1-ce'
adminSecret = 'o_A^0hsy0w!yv+Wb_q_ggrz__I8dWs5i'
webhookSecret = 'H1+!OZAfeb_4FHAQRZ67aXqKtVwV=sSA'

[[global.environment]]
name = 'NHOST_GRAPHQL_URL'
value = 'https://yfnaaqdhstomxncwctej.graphql.ap-south-1.nhost.run/v1'

[[global.environment]]
name = 'NHOST_STORAGE_URL'
value = 'https://yfnaaqdhstomxncwctej.storage.ap-south-1.nhost.run/v1'

[[global.environment]]
name = 'NHOST_FUNCTIONS_URL'
value = 'https://yfnaaqdhstomxncwctej.functions.ap-south-1.nhost.run/v1'

[[global.environment]]
name = 'NHOST_SUBDOMAIN'
value = 'yfnaaqdhstomxncwctej'

[[global.environment]]
name = 'NHOST_REGION'
value = 'ap-south-1'